### ISSUE TITLE
Budget Tracking

### ISSUE THREAD

**Issue by jonLicari** [jonLicari/finance-report#10]
# Description
- [ ] take in file containing user's custom budget
- [ ] compare calculated expense data with budget 
- [ ] present graphical analysis of the comparison
