### ISSUE TITLE
Update Category List

### ISSUE THREAD

**Issue by jonLicari** [jonLicari/finance-report#15]
Recently slimmed down Categories/ Subsets to focus only on what is important to have detail on.

| Food	| Shopping	| Transportation	| Utilities	| Entertainment	| Career |	Health |	Income	|
| ----- | --------- | --------------- | --------- | ------------- | ------ | ------- | -------- |
| Restaurant	| Clothing	| Gas	| Phone	| Gaming	| | | Salary | 	
| Grocery	|Gifts	| Transit	| Internet	| Events	| | | Other	|
| Alcohol	|Other	| Insurance	| Hydro	| Other	|			
|	|	| Car	| Rent | 					
|	|	| |	Tenant Insurance |	

# Tasks
- [ ] update actual data to accommodate these changes (sample-data.xlsx already incorporates changes)
- [ ] Update plots and categorical calculations
- [ ] create a release tag since this version will mean previous datasets will not be compatible
